stages:
    - build
    - test
build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        path:
            - build/
test:
    stage: test
    script:
        - echo "test"
        - test -f build/info.txt
